stages:
    - build
    - test

build:
    stage: build
    script:
        - cd safar
        - ./gradlew assemble

test:
    stage: test
    script:
        - cd safar
        - ./gradlew test

after_script:
    - echo "End CI"
