stages:
    - build
    - sonar
    - test

build:
    stage: build
    script:
        - cd safar
        - ./gradlew assemble
        
sonar:
    stage: sonar
    script:
        - cd safar
        - ./gradlew sonarqube -D "sonar.projectKey=safarTravelApp" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=069605e56d35788dfa2af17071dbe6b604810520"

test:
    stage: test
    script:
        - cd safar
        - ./gradlew test

after_script:
    - echo "End CI"
